import { currentUser } from '@auth/index';
import { auth } from '@clerk/nextjs';
import type { Metadata } from 'next';
import Navbar from '@components/layout/ui/Navbar';
import prisma from '@prisma/prisma';
import { redirect } from 'next/navigation';
import { Providers } from './providers';
import { TUser } from './_utils/context/CurrentUserContext';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default async function Layout({
	children,
}: {
	children: React.ReactNode;
}) {
	const { userId } = auth();
	const temp = await currentUser();

	if (!userId || !temp) {
		await prisma.$disconnect();
		return redirect('/sign-in');
	}

	const user = await prisma.user.findUnique({
		where: {
			clerkId: userId,
		},
		include: {
			UserOnWorkSpace: {
				where: {
					userId: temp.id,
				},
				include: {
					workSpace: {
						include: {
							Space: true,
						},
					},
				},
			},
		},
	});
	await prisma.$disconnect();

	return (
		<div className="flex h-full w-full flex-col">
			<Providers currentUser={user || ({} as TUser)}>
				<Navbar username={temp.username} />
				{children}
			</Providers>
		</div>
	);
}
