import type { Metadata } from 'next';
import { PiPlus } from 'react-icons/pi';
import prisma from '@prisma/prisma';
import { currentUser as getClerkCurrentUser } from '@clerk/nextjs';
import { redirect } from 'next/navigation';
import Spaces from './_components/Spaces';
import Workspaces from './_components/Workspaces';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default async function Layout({
	children,
}: {
	children: React.ReactNode;
}) {
	const currentUser = await getClerkCurrentUser();
	if (!currentUser) return redirect('/sign-in');

	const user = await prisma.user.findUnique({
		where: {
			clerkId: currentUser.id,
		},
		include: {
			UserOnWorkSpace: {
				include: {
					workSpace: true,
				},
			},
		},
	});

	if (!user) return <div>Erro</div>;
	const workSpaces = user.UserOnWorkSpace.flatMap((u) => u.workSpace);

	return (
		<div className="mx-auto mt-5 flex w-full max-w-5xl gap-5 p-5">
			<div className="flex w-full max-w-[256px] flex-col gap-3">
				<div className="flex flex-col gap-1">
					<Spaces />
				</div>
				<hr />
				<div className="flex flex-col items-center gap-2">
					<div className="flex w-full items-center justify-between pl-3 text-xs font-semibold text-slate-700">
						<span>Áreas de trabalho</span>
						<button className="btn btn-ghost btn-sm" type="button">
							<PiPlus />
						</button>
					</div>
					<div className="flex w-full">
						<Workspaces workspaces={workSpaces} />
					</div>
				</div>
			</div>
			{children}
		</div>
	);
}
