import type { Metadata } from 'next';
import SocketContextProviderComponent from '@/utils/contexts/SocketContext/Provider';
import PointerBoard from '@/components/PointerBoard';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function Layout({
	children,
}: {
	children: React.ReactNode;
}): React.ReactNode {
	return (
		<SocketContextProviderComponent>
			<PointerBoard />
			{children}
		</SocketContextProviderComponent>
	);
}
