import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import SocketContextProviderComponent from '@/utils/contexts/SocketContext/Provider';
import PointerBoard from '@/components/PointerBoard';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}): React.ReactNode {
	return (
		<html lang="pt-BR" className="overflow-hidden">
			<body className={inter.className}>
				<SocketContextProviderComponent>
					<PointerBoard />
					{children}
				</SocketContextProviderComponent>
			</body>
		</html>
	);
}
