import type { Metadata } from 'next';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function Layout({
	children,
}: {
	children: React.ReactNode;
}): React.ReactNode {
	return (
		<div className="flex h-full w-full items-center justify-center bg-slate-100">
			{children}
		</div>
	);
}
