export const metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js',
};

export default function Layout({ children }: { children: React.ReactNode }) {
	return (
		<div className="flex h-full w-full items-center justify-center bg-white md:bg-slate-100">
			{children}
		</div>
	);
}
